//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WelfareLotteryClient.DBModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WelfareLotteryEntities : DbContext
    {
        public WelfareLotteryEntities()
            : base("name=WelfareLotteryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Administrator> Administrator { get; set; }
        public virtual DbSet<AspNetRoleClaims> AspNetRoleClaims { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<LotteryStation> LotteryStation { get; set; }
        public virtual DbSet<RewardCardInfo> RewardCardInfo { get; set; }
        public virtual DbSet<Salesclerk> Salesclerk { get; set; }
        public virtual DbSet<SportLottery> SportLottery { get; set; }
        public virtual DbSet<SportLotteryGameType> SportLotteryGameType { get; set; }
        public virtual DbSet<StationManageType> StationManageType { get; set; }
        public virtual DbSet<StationModifiedInfo> StationModifiedInfo { get; set; }
        public virtual DbSet<StationModifiedType> StationModifiedType { get; set; }
        public virtual DbSet<StationRegion> StationRegion { get; set; }
        public virtual DbSet<WelfareLotteryGameType> WelfareLotteryGameType { get; set; }
    }
}
