//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WelfareLotteryClient.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SportLottery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SportLottery()
        {
            this.LotteryStations = new HashSet<LotteryStation>();
        }
    
        public Nullable<int> GameTypeId { get; set; }
        public int Id { get; set; }
        public Nullable<System.DateTime> IncomingDate { get; set; }
        public bool IsInstall { get; set; }
        public string LotteryCode { get; set; }
        public string PhoneNumber { get; set; }
        public string Relation { get; set; }
        public string SportLotteryHostName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LotteryStation> LotteryStations { get; set; }
        public virtual SportLotteryGameType SportLotteryGameType { get; set; }
    }
}
