//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WelfareLotteryClient.DBModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WelfareLotteryEntities : DbContext
    {
        public WelfareLotteryEntities()
            : base("name=WelfareLotteryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Administrator> Administrators { get; set; }
        public virtual DbSet<AspNetRoleClaim> AspNetRoleClaims { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<LotteryStation> LotteryStations { get; set; }
        public virtual DbSet<RewardCardInfo> RewardCardInfoes { get; set; }
        public virtual DbSet<Salesclerk> Salesclerks { get; set; }
        public virtual DbSet<SportLottery> SportLotteries { get; set; }
        public virtual DbSet<SportLotteryGameType> SportLotteryGameTypes { get; set; }
        public virtual DbSet<StationManageType> StationManageTypes { get; set; }
        public virtual DbSet<StationModifiedInfo> StationModifiedInfoes { get; set; }
        public virtual DbSet<StationModifiedType> StationModifiedTypes { get; set; }
        public virtual DbSet<StationRegion> StationRegions { get; set; }
        public virtual DbSet<WelfareLotteryGameType> WelfareLotteryGameTypes { get; set; }
    }
}
